[[call]]
call_type = "deploy"
class_hash = "0x54af96825d987ca89cf320f7c5a8031017815d884cff1592e8ff6da309f3ca6"
inputs = [
    "0x1",
    "0x18e4a8e2badb5f5950758f46f8108e2c5d357b07",
    "0x0",
    "0x5a6c0f84179d695f0b598cc5d0be50421c247da95cfe63e4cd66fc27f32dfe6",
]
id = "commitments_inbox"
unique = false

[[call]]
call_type = "deploy"
class_hash = "0x2055a6a11f644201f229c1ecdc10912f20ae0f51ac8aa6ef921c58e52bae404"
inputs = ["commitments_inbox"]
id = "headers_store"
unique = false

[[call]]
call_type = "deploy"
class_hash = "0x74c929cfd9fd8d7577d8c7b8102010d925cbc1b1475a5873047099a4e00dab7"
inputs = ["headers_store"]
id = "evm_facts_registry"
unique = false

[[call]]
call_type = "invoke"
contract_address = "commitments_inbox"
function = "set_headers_store"
inputs = ["headers_store"]

[[call]]
call_type = "deploy"
class_hash = "0x67ae27cd294fea085fc3b63cd8b872774cc1ba92bd54864c267eda6fa81a493"
inputs = ["headers_store"]
id = "timestamp_remappers"
unique = false