[[call]]
call_type = "deploy"
class_hash = "0x54af96825d987ca89cf320f7c5a8031017815d884cff1592e8ff6da309f3ca6"
inputs = [
    "0x1",
    "0x260FdcB223fBf581ee85FFe2bEf6C59Eb465dB28",
    "0x0",
    "0x5a6c0f84179d695f0b598cc5d0be50421c247da95cfe63e4cd66fc27f32dfe6",
]
id = "commitments_inbox"
unique = false

[[call]]
call_type = "deploy"
class_hash = "0x1b0eeb6325cbb7874f5ee8d3f59df2617113073b52911cfca9077ec9d581555"
inputs = ["commitments_inbox"]
id = "headers_store"
unique = false

[[call]]
call_type = "deploy"
class_hash = "0x3211460c883d24937aa616ec31d01a3f09fafb053439b9b1b7bedf72df00ce"
inputs = ["headers_store"]
id = "evm_facts_registry"
unique = false

[[call]]
call_type = "invoke"
contract_address = "commitments_inbox"
function = "set_headers_store"
inputs = ["headers_store"]

[[call]]
call_type = "deploy"
class_hash = "0xa5816245847010c159074cd8779a3fb38c1e0a887ad63f5b0f06ab9a9cb788"
inputs = ["headers_store"]
id = "timestamp_remappers"
unique = false