[[call]]
call_type = "deploy"
class_hash = "0x3e9609ed86823420a71bf49659692e3dced77187db80c44c9835c1dd6971292"
inputs = [
    "0x1",
    "0x30DdE9bC96D800fF70383c74a95141E156Db1DF0",
    "0x0",
    "0x5a6c0f84179d695f0b598cc5d0be50421c247da95cfe63e4cd66fc27f32dfe6",
]
id = "commitments_inbox"
unique = false

[[call]]
call_type = "deploy"
class_hash = "0x43b8bbd6d131703af8b288225caa29dc4d0cdd807b9be1ddcf9483d836a5684"
inputs = ["commitments_inbox"]
id = "headers_store"
unique = false

[[call]]
call_type = "deploy"
class_hash = "0x476dd358f684b29ef00299a8bcefa3cbde0f46d4df8716f2fde06555ece0c7b"
inputs = ["headers_store"]
id = "evm_facts_registry"
unique = false

[[call]]
call_type = "invoke"
contract_address = "commitments_inbox"
function = "set_headers_store"
inputs = ["headers_store"]

[[call]]
call_type = "deploy"
class_hash = "0x73305243f4fa52b5a26b75bcb2ace081e28eb365239b58723ae643f63875078"
inputs = ["headers_store"]
id = "timestamp_remappers"
unique = false