[[call]]
call_type = "deploy"
class_hash = "0x18c9ce7ffa88f15bd1fcda1350cb66cc5c369bc924e5dc108be1c9317298c99"
inputs = [
    "0x1",
    "0x30DdE9bC96D800fF70383c74a95141E156Db1DF0",
    "0x0",
    "0x5a6c0f84179d695f0b598cc5d0be50421c247da95cfe63e4cd66fc27f32dfe6",
]
id = "commitments_inbox"
unique = false

[[call]]
call_type = "deploy"
class_hash = "0x48d1f93626722872832416241a30c20bb77403b48249e65bebae67ab7a5329"
inputs = ["commitments_inbox"]
id = "headers_store"
unique = false

[[call]]
call_type = "deploy"
class_hash = "0x5bae175b97cd8d6ce988ee862be7081397d36a8044a4d7e9b1bd810532daba9"
inputs = ["headers_store"]
id = "evm_facts_registry"
unique = false

[[call]]
call_type = "invoke"
contract_address = "commitments_inbox"
function = "set_headers_store"
inputs = ["headers_store"]

[[call]]
call_type = "deploy"
class_hash = "0x2e7de0c6a2fd1759b02cc59998f6267e5d1b73852d1ec556594269c9bc48b63"
inputs = ["headers_store"]
id = "timestamp_remappers"
unique = false