[[call]]
call_type = "deploy"
class_hash = "0x636debf6067e2fd953c4a2ceb6ca3b93d97474a725816a3ea438d3f79eb7512"
inputs = [
    "0x1",
    "0xdF32BADD47BEef951a77Da5dbfA14E2D65dF3A20",
    "0x0",
    "0x5a6c0f84179d695f0b598cc5d0be50421c247da95cfe63e4cd66fc27f32dfe6",
]
id = "commitments_inbox"
unique = false

[[call]]
call_type = "deploy"
class_hash = "0x5415fef5becee8d69aeaeaed8b12d2e0505c9f045b679ef2b40163cc54dae02"
inputs = ["commitments_inbox"]
id = "headers_store"
unique = false

[[call]]
call_type = "deploy"
class_hash = "0x59bc294565250247b8d77921c84c96a312748496245fb11b3f1c37be6920a21"
inputs = ["headers_store"]
id = "evm_facts_registry"
unique = false

[[call]]
call_type = "invoke"
contract_address = "commitments_inbox"
function = "set_headers_store"
inputs = ["headers_store"]

[[call]]
call_type = "deploy"
class_hash = "0x6b83039caf2042ee17d07853c0c24a021f4301f6c49a778fe7f690b45b2fc8f"
inputs = ["headers_store"]
id = "timestamp_remappers"
unique = false